import time
import requests
import json
import sys

# ─── Configuration ─────────────────────────────────────────────────────────────
BASE_URL = "http://127.0.0.1:8080/api/v1"

# ANSI Color Codes for beautiful terminal output
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def print_step(step_num, message):
    print(f"\n{Colors.BOLD}{Colors.CYAN}[STEP {step_num}]{Colors.ENDC} {Colors.BOLD}{message}{Colors.ENDC}")

def print_success(message):
    print(f"  {Colors.GREEN}✔ {message}{Colors.ENDC}")

def print_error(message):
    print(f"  {Colors.FAIL}✘ {message}{Colors.ENDC}")

def print_info(message):
    print(f"  {Colors.BLUE}ℹ {message}{Colors.ENDC}")


# ─── Data Payload ──────────────────────────────────────────────────────────────
# We formulate 3 transactions: two normal, and one obvious anomaly.
# The anomaly is a massive SWIFT transfer from a high-risk region, 
# which the IsolationForest model will almost certainly flag as an outlier.
TRANSACTIONS_PAYLOAD = {
    "transactions": [
        {
            "transaction_id": "txn-norm-001",
            "amount": 1250.50,
            "currency": "USD",
            "transaction_type": "ACH",
            "region": "North America",
            "account_metadata": {
                "account_holder": "Alice Smith",
                "historical_avg_transaction": 1100.00
            }
        },
        {
            "transaction_id": "txn-norm-002",
            "amount": 450.00,
            "currency": "GBP",
            "transaction_type": "Credit Card",
            "region": "Europe",
            "account_metadata": {
                "account_holder": "Bob Jones",
                "historical_avg_transaction": 300.00
            }
        },
        {
            "transaction_id": "txn-anom-999",
            "amount": 8500000.00,
            "currency": "EUR",
            "transaction_type": "SWIFT",
            "region": "High-Risk Jurisdiction",
            "account_metadata": {
                "account_holder": "Shell Company XYZ",
                "historical_avg_transaction": 50.00
            }
        }
    ]
}


def main():
    print(f"{Colors.HEADER}═══════════════════════════════════════════════════════════════")
    print(f"  VERITAS PLATFORM — END-TO-END DATABASE SEEDING SCRIPT")
    print(f"═══════════════════════════════════════════════════════════════{Colors.ENDC}\n")

    # ─── Step 1: Ingest Transactions ──────────────────────────────────────────
    print_step(1, "Ingesting Sample Transactions")
    try:
        res_ingest = requests.post(f"{BASE_URL}/ingest", json=TRANSACTIONS_PAYLOAD)
        res_ingest.raise_for_status()
        print_success(f"Successfully ingested {len(TRANSACTIONS_PAYLOAD['transactions'])} transactions.")
    except requests.exceptions.RequestException as e:
        print_error(f"Failed to ingest transactions. Is the Flask server running at {BASE_URL}?")
        print_error(str(e))
        sys.exit(1)


    # ─── Step 2: Run ML Prediction ────────────────────────────────────────────
    print_step(2, "Running Machine Learning Isolation Forest")
    try:
        res_predict = requests.post(f"{BASE_URL}/predict", json=TRANSACTIONS_PAYLOAD)
        res_predict.raise_for_status()
        data_predict = res_predict.json()
        
        results = data_predict.get("results", [])
        print_success(f"ML scored {len(results)} transactions.")
        
        # Find the alert ID generated by the anomaly
        alert_id = None
        for r in results:
            if r.get("is_anomaly"):
                alert_id = r.get("alert_id")
                print_info(f"Anomaly detected! Transaction ID: {r.get('transaction_id')} -> Alert ID: {alert_id}")
                break
        
        if not alert_id:
            print_warning("No anomalies were detected by the model. The advise step requires an alert_id.")
            sys.exit(0)

    except requests.exceptions.RequestException as e:
        print_error(f"Failed to score transactions.")
        print_error(str(e))
        sys.exit(1)


    # ─── Step 3: Trigger Multi-Agent System (Virtual Risk Committee) ──────────
    print_step(3, f"Triggering Virtual Risk Committee for Alert {alert_id}")
    print_info("The AI Agents are now investigating the transaction. This may take 30-90 seconds...")
    
    start_time = time.time()
    try:
        # Increase timeout drastically to accommodate slow LLM inference
        res_advise = requests.post(
            f"{BASE_URL}/advise", 
            json={"alert_id": alert_id}, 
            timeout=180
        )
        res_advise.raise_for_status()
        
        elapsed = time.time() - start_time
        print_success(f"Multi-Agent Risk Committee completed in {elapsed:.1f} seconds!")
        
        report = res_advise.json().get("report", "No report returned.")
        
        print(f"\n{Colors.BOLD}=== FINAL EXECUTIVE BRIEF & SAR DRAFT ==={Colors.ENDC}")
        print(f"{Colors.GREEN}{report}{Colors.ENDC}")
        print(f"{Colors.BOLD}========================================={Colors.ENDC}\n")

    except requests.exceptions.Timeout:
        print_error("The request timed out. The LLM took longer than 3 minutes to respond.")
        sys.exit(1)
    except requests.exceptions.RequestException as e:
        print_error("Failed to run the Virtual Risk Committee.")
        print_error(str(e))
        try:
            print_error(f"Response: {e.response.text}")
        except:
            pass
        sys.exit(1)

    print(f"{Colors.HEADER}Database Seeding and AI Advisory Pipeline Complete!{Colors.ENDC}")

if __name__ == "__main__":
    main()
